apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: app/backend
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 3000
                  env:
                    - name: NODE_ENV
                      value: production


                    - name: MAIN_DATABASE_HOST
                      value: main-db


                    - name: MAIN_DATABASE_USERNAME
                      valueFrom:
                          secretKeyRef:
                              name: main-db-secrets
                              key: main_database_username

                    - name: MAIN_DATABASE_PASSWORD
                      valueFrom:
                          secretKeyRef:
                              name: main-db-secrets
                              key: main_database_password

                    - name: MAIN_DATABASE
                      valueFrom:
                        secretKeyRef:
                          name: main-db-secrets
                          key: main_database


                    - name: REDIS_HOST
                      value: redis
                    - name: REDIS_PORT
                      value: '6379'

                    - name: JWT_SECRET
                      valueFrom:
                        secretKeyRef:
                          name: other-secrets
                          key: jwt-secret


                    - name: PROJECT_NAME
                      value: App
                    - name: PROJECT_DOMAIN
                      value: app.com
                    - name: PROJECT_URL
                      value: http://app.com

                    - name: MAIL_HOST
                      valueFrom:
                        secretKeyRef:
                          name: email-secret
                          key: mail_host

                    - name: MAIL_PORT
                      valueFrom:
                        secretKeyRef:
                          name: email-secret
                          key: mail_port

                    - name: MAIL_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: email-secret
                          key: mail_username

                    - name: MAIL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: email-secret
                          key: mail_password

                    - name: MAIL_DEFAULT_FROM
                      valueFrom:
                        secretKeyRef:
                          name: email-secret
                          key: mail_default_from


                    - name: USER_EMAIL
                      valueFrom:
                        secretKeyRef:
                          name: default-user-secret
                          key: user_email

                    - name: USER_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: default-user-secret
                          key: user_password

                    - name: USER_NAME
                      value: Admin
