FROM node:16.14.0-alpine3.15 as builder

WORKDIR /app

COPY package.json ./

RUN npm install -g npm@8.3.0

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.19.9-alpine

COPY --from=builder /app/frontend/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
