version: '3.9'
services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: dockerfile
        restart: always
        ports:
            - 80
        environment:
            VIRTUAL_HOST: app.com
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: app.com
            LETSENCRYPT_EMAIL: info@app.com
            REACT_APP_API_BASE_URL: http://127.0.0.1:4000

    backend:
        container_name: backend
        build: ./backend
        restart: always
        depends_on:
            - mysql_master
            - redis_master
        ports:
          - 4000
        env_file:
            - .env
        environment:
            VIRTUAL_HOST: api.app.com
            VIRTUAL_PORT: 4000

            LETSENCRYPT_HOST: api.app.com
            LETSENCRYPT_EMAIL: info@app.com

            NODE_ENV: production
            PORT: 4000

            MYSQL_HOST: mysql_master

            REDIS_HOST: redis_master
            REDIS_PORT: 6379

            PROJECT_NAME: App
            PROJECT_DOMAIN: app.com
            PROJECT_URL: http://app.com

    mysql_master:
        container_name: mysql_master
        image: mysql:8.0.23
        restart: always
        command: "--default-authentication-plugin=mysql_native_password --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
        security_opt:
            - seccomp:unconfined
        volumes:
          - mysql_master-volume:/var/lib/mysql
        env_file:
            - .env.mysql

    redis_master:
        container_name: redis_master
        image: redis:alpine3.13
        restart: always
        volumes:
            - redis_master-volume:/data

volumes:
    mysql_master-volume:
    redis_master-volume:

networks:
    default:
        external: true
        name: proxy
