version: '3'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - 80:80
        expose:
            - 80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    mysql-db:
        container_name: admin_mysql-db
        build: ./infra/docker/db/mysql
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql-db-volume:/var/lib/mysql
        ports:
            - 3306:3306
        expose:
            - 3306
        env_file:
            - mysql.env
        security_opt:
            - seccomp:unconfined

    redis:
        container_name: admin_redis
        build: ./infra/docker/db/redis
        volumes:
            - redis-volume:/data
        ports:
            - 6379:6379

    backend:
        container_name: admin_backend
        restart: always
        build:
            context: ./backend
        volumes:
            - '/app/node_modules'
            - ./backend:/app
        ports:
            - 3000:3000
        expose:
            - 3000
        depends_on:
            - mysql-db
            - redis
        env_file:
            - .env

    dashboard:
        container_name: admin_dashboard
        build:
            context: ./frontend
            dockerfile: Dockerfile.dashboard.dev
        restart: always
        stdin_open: true
        ports:
            - 3001:3001
        volumes:
            - '/app/node_modules'
            - ./frontend:/app
        environment:
            NODE_ENV: development
            CHOKIDAR_USEPOLLING: 'true'
            VIRTUAL_HOST: app.com
            VIRTUAL_PORT: 3001
        expose:
            - 3001

volumes:
    mysql-db-volume:
    redis-volume:
