version: '3.7'
services:
    proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        restart: always
        ports:
            - 80:80
            - 443:443
        expose:
            - 80
            - 443
        volumes:
            - html:/usr/share/nginx/html
            - dhparam:/etc/nginx/dhparam
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro
        labels:
            - 'com.github.jrcs.letsencrypt_proxy_companion.proxy'

    proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: proxy-letsencrypt
        restart: always
        depends_on:
            - proxy
        volumes:
            - html:/usr/share/nginx/html
            - vhost:/etc/nginx/vhost.d
            - certs:/etc/nginx/certs:rw
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            DEFAULT_EMAIL: admin@quickerapp.net
            PROXY_CONTAINER: proxy

volumes:
    html:
    dhparam:
    vhost:
    certs:

networks:
    default:
        name: proxy
