apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                - name: redis
                  image: redis:alpine3.13
                  ports:
                      - containerPort: 6379
                        name: redis
                  volumeMounts:
                  - name: redis-volume
                    mountPath: /data

            volumes:
            - name: redis-volume
              persistentVolumeClaim:
                claimName: redis-pv-claim