apiVersion: apps/v1
kind: Deployment
metadata:
    name: main-db-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: main-db
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: main-db
        spec:
            containers:
                - name: main-db
                  image: mysql:8.0.23
                  args: ["--default-authentication-plugin=mysql_native_password"]
                  env:
                  - name: MYSQL_DATABASE
                    valueFrom:
                        secretKeyRef:
                          name: main-db-secrets
                          key: main_database

                  - name: MYSQL_ROOT_PASSWORD
                    valueFrom:
                        secretKeyRef:
                          name: main-db-secrets
                          key: main_database_password

                  ports:
                      - containerPort: 3306
                        name: main-db
                  volumeMounts:
                  - name: main-db-volume
                    mountPath: /var/lib/mysql

            volumes:
            - name: main-db-volume
              persistentVolumeClaim:
                claimName: main-db-pv-claim
