apiVersion: apps/v1
kind: Deployment
metadata:
    name: db-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: db
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: db
        spec:
            containers:
                - name: db
                  image: mysql:8.0.23
                  command: ["--default-authentication-plugin=mysql_native_password"]
                  env:
                  - name: MYSQL_DATABASE
                    value: main
                    # Use secret
                  - name: MYSQL_ROOT_PASSWORD
                    value: password
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                  - name: mysql-volume
                    mountPath: /var/lib/mysql

            volumes:
            - name: mysql-volume
              persistentVolumeClaim:
                claimName: mysql-pv-claim